services:
  exporter:
    image: nutanix_exporter:1.3
    container_name: nutanix-exporter
    command:
#      - "-log.level=DEBUG"
      - "-nutanix.conf=/config.yml"
    ports:
      - 9405:9405
    volumes:
      - ./config.yml:/config.yml
    networks:
      - promgraf_grafana-prometheus

networks:
  promgraf_grafana-prometheus:
    external: true
